### ISSUE TITLE
请问预训练模型mae_visualize_vit_base文件该放在文件夹的哪个位置

### ISSUE THREAD

**Issue by mostimali** [zhangzilongc/MMR#10]
请问预训练模型mae_visualize_vit_base文件该放在文件夹的哪个位置

**Comment by zhangzilongc** [comment]
> 请问预训练模型mae_visualize_vit_base文件该放在文件夹的哪个位置

可以放在MMR文件下，需要修改MMR.yaml文件里TRAIN MMR model_chkpt，把这个后面的文件名改为你现在放的文件目录，比如放在MMR文件下就是"./mae_visualize_vit_base.pth"

**Comment by lishenbin** [comment]
好的, 十分感谢

**Comment by lishenbin** [comment]
好的, 十分感谢^_^
另外我还发现下载好的AeBAD数据集中都若干图片都是受损无法查看的; 这是我下载时出错的吗

**Comment by mostimali** [comment]
好的, 十分感谢^_^
另外我还发现下载好的AeBAD数据集中的若干张图片都是受损无法查看的; 这是我下载时出错的吗

**Comment by zhangzilongc** [comment]
> 好的, 十分感谢^_^ 另外我还发现下载好的AeBAD数据集中的若干张图片都是受损无法查看的; 这是我下载时出错的吗

用什么下的

**Comment by mostimali** [comment]
谷歌云盘

**Comment by zhangzilongc** [comment]
试试天翼有没有问题

**Comment by lishenbin** [comment]
![Uploading 0F1F1EF17A1AD0EA08E4660F713A3A3F.png…]()

**Comment by mostimali** [comment]
好的, 我试一下

**Comment by zhangzilongc** [comment]
我试过用谷歌下没问题，文件里的图像没问题

**Comment by mostimali** [comment]
我这边用天翼下载还是有受损图片, 而且和谷歌云盘里面那些受损图片都是一样的...

**Comment by zhangzilongc** [comment]
受损文件的名字，我看看

**Comment by zhangzilongc** [comment]
受损的目录

**Comment by mostimali** [comment]
比如说AeBAD\AeBAD_S\train\good\background的._IMG_7287

**Comment by zhangzilongc** [comment]
我知道了，这些文件都是mac电脑自动生成的，我用mac看不见这些文件，但是系统能看见，你把这些删了就可以了，真正用于训练的都是IMG_7287.png格式的，._IMG都是隐藏文件，苹果电脑生成的

**Comment by mostimali** [comment]
嗷嗷, 明白了; 谢谢大佬

**Comment by xin94wang** [comment]
> > 请问预训练模型mae_visualize_vit_base文件该放在文件夹的哪个位置
> 
> 可以放在MMR文件下，需要修改MMR.yaml文件里TRAIN MMR model_chkpt，把这个后面的文件名改为你现在放的文件目录，比如放在MMR文件下就是"./mae_visualize_vit_base.pth"

请问mae_visualize_vit_base.pth这个预训练模型是您以前训练过后生成的权重文件，还是我们训练需要用到的文件啊？如果我改变数据集，是不是仍然需要使用mae_visualize_vit_base.pth这个文件呢？

**Comment by zhangzilongc** [comment]
> > > 请问预训练模型mae_visualize_vit_base文件该放在文件夹的哪个位置
> > 
> > 
> > 可以放在MMR文件下，需要修改MMR.yaml文件里TRAIN MMR model_chkpt，把这个后面的文件名改为你现在放的文件目录，比如放在MMR文件下就是"./mae_visualize_vit_base.pth"
> 
> 请问mae_visualize_vit_base.pth这个预训练模型是您以前训练过后生成的权重文件，还是我们训练需要用到的文件啊？如果我改变数据集，是不是仍然需要使用mae_visualize_vit_base.pth这个文件呢？

是的，如果在新的数据集上训练，还要用这个开始训练
