### ISSUE TITLE
Anomaly map

### ISSUE THREAD

**Issue by Ehteshamciitwah** [zhangzilongc/MMR#11]
Hello, Thank you for your excellent work. I have a query regarding the anomaly map. In the paper, you mentioned the process of computing anomaly maps, but you used cosine similarity in the code. Is their anything I missing. Can you please elaborate on the difference between paper and implementation? 
Code:
https://github.com/zhangzilongc/MMR/blob/22d1b171687509024e6f5b53b5a5e772d653d32b/models/MMR/utils.py#L74
Paper: 

![image](https://github.com/zhangzilongc/MMR/assets/79190474/5c376718-b033-438a-b7bf-adbb6c54b3ca)

**Comment by zhangzilongc** [comment]
> Hello, Thank you for your excellent work. I have a query regarding the anomaly map. In the paper, you mentioned the process of computing anomaly maps, but you used cosine similarity in the code. Is their anything I missing. Can you please elaborate on the difference between paper and implementation? Code:
> 
> https://github.com/zhangzilongc/MMR/blob/22d1b171687509024e6f5b53b5a5e772d653d32b/models/MMR/utils.py#L74
> 
> 
> Paper:
> ![image](https://private-user-images.githubusercontent.com/79190474/328541209-5c376718-b033-438a-b7bf-adbb6c54b3ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODkwOTIsIm5iZiI6MTcxNTA4ODc5MiwicGF0aCI6Ii83OTE5MDQ3NC8zMjg1NDEyMDktNWMzNzY3MTgtYjAzMy00MzhhLWI3YmYtYWRiYjZjNTRiM2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMzMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OWRiNjg5YjJkNmQzN2FhODA1MWYzN2E0M2UwZTdiZTE0YzE5NWI0YTY2YTJiYWUzMGEyOGU1NWEyNzlhMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QXj9i2LLc6PnPQgh57vSKmwIRP7qs9CmwyaanQ6sHj4)

Mathematically this is equivalent. Cosine similarity is the sum of each element of two vectors multiplied point by point.
