### ISSUE TITLE
Looking forward to the AeBAD dataset !!!

### ISSUE THREAD

**Issue by JiankaiTu** [zhangzilongc/MMR#2]
We sincerely look forward to an early release of the AeBAD dataset!

**Comment by zhangzilongc** [comment]
Thanks for your interest in our work! We will release our dataset in early May.

**Comment by nicebro123** [comment]
Thank you very much for your work!

**Comment by zhangzilongc** [comment]
> 

We have released the download link and added the codes of the evaluation on AeBAD.

**Comment by seefun** [comment]
Thank you very much for your great work!

**Comment by zhangzilongc** [comment]
>
