### ISSUE TITLE
imagesize修改

### ISSUE THREAD

**Issue by shuaiqidexiaojiejie** [zhangzilongc/MMR#4]
你好，很高兴可以在Github上收到您的回复。目前我正遇见一个难题，希望能得到您的帮助。我在用您在Github上的MMR-master 模型训练我自己的数据集(图片的大小为1280 x 1024)时，想让最后的结果显示为256x256的热力图。我修改了imagesize
但是运行时出现了一下错误，能帮我解决下么;
![2023-05-22 12-11-11屏幕截图](https://github.com/zhangzilongc/MMR/assets/101921170/93e228da-da8e-4cae-9ffe-1359a2e6951f)
![2023-05-22 12-18-44屏幕截图](https://github.com/zhangzilongc/MMR/assets/101921170/ff737fb0-4596-451e-b2ce-aa02bf9c375a)

**Comment by zhangzilongc** [comment]
> 你好，很高兴可以在Github上收到您的回复。目前我正遇见一个难题，希望能得到您的帮助。我在用您在Github上的MMR-master 模型训练我自己的数据集(图片的大小为1280 x 1024)时，想让最后的结果显示为256x256的热力图。我修改了imagesize 但是运行时出现了一下错误，能帮我解决下么; ![2023-05-22 12-11-11屏幕截图](https://user-images.githubusercontent.com/101921170/239802780-93e228da-da8e-4cae-9ffe-1359a2e6951f.png) ![2023-05-22 12-18-44屏幕截图](https://user-images.githubusercontent.com/101921170/239802790-ff737fb0-4596-451e-b2ce-aa02bf9c375a.png)

我已经修改了dataset里mvtec文件和models中的MMR文件，你现在可以更改image size位256
