### ISSUE TITLE
Train and Test process of AeBAD-S

### ISSUE THREAD

**Issue by BITWN** [zhangzilongc/MMR#6]
您好，阅读完论文之后，没有特别理解用AeBAD-S数据集在训练及test时要怎么分配数据，想和您确认：
训练数据时：train中的所有图片都会作为输入，最终生成1个异常检测模型
test即推理时：按照same, background, illumination, 和view这4个维度分别推理，然后每个维度分别计算指标(如论文结果)吗？

期待您的回答，十分感谢！

**Comment by zhangzilongc** [comment]
对的，是这样的，代码里也是这么写的，你可以看train.py里面33行，还有后续的AeBAD_S里的数据集分配的代码

**Comment by BITWN** [comment]
十分感谢您的回答！
