### ISSUE TITLE
Save_model

### ISSUE THREAD

**Issue by Ehteshamciitwah** [zhangzilongc/MMR#8]
Hello,

Thank you for your work.
I trained your model on the default setting using the Aebad_S dataset. But I cannot see the saved model although I use the save model flag as true. 

Please elaborate on how to save the model and load it back to test on different images. How we can resume the model from ckpt.  In addition, If possible how we can train on the custom dataset? Thank you for your time.

**Comment by zhangzilongc** [comment]
I’m sorry, in this version, I did not add the function of saving model and test. I will add this in the future when I am free.

**Comment by zhangzilongc** [comment]
> Hello,
> 
> Thank you for your work. I trained your model on the default setting using the Aebad_S dataset. But I cannot see the saved model although I use the save model flag as true.
> 
> Please elaborate on how to save the model and load it back to test on different images. How we can resume the model from ckpt. In addition, If possible how we can train on the custom dataset? Thank you for your time.

I’m sorry, in this version, I did not add the function of saving model and test. I will add this in the future when I am free.

**Comment by Ehteshamciitwah** [comment]
Thank you for your prompt response. Please keep us updated.
